homeassistant:
  #Location information
  # latitude: !secret lat_secret
  # longitude: !secret lon_secret
  # time_zone: America/New_York
  # elevation: 130
  # unit_system: imperial
  
  # Customization
  # name: Home
  customize: !include structure/customize.yaml
  customize_domain: {}
  customize_glob: {}
  
http:
  api_password: !secret ha_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret url4_secret
  
recorder:
  purge_interval: 2
  purge_keep_days: 7
  db_url: !secret db_secret

system_health:

person:

logger: 
  default: error
  logs:
    homeassistant.components.calendar.visitor: critical
    homeassistant.components.calendar.vacation: critical
    homeassistant.components.sensor.cert_expiry: critical
    homeassistant.components.haveibeenpwned: critical
    homeassistant.custom_components.weatheralerts: critical
    #homeassistant.components.tplink: debug
    #homeassistant.components.stream: debug
    homeassistant.custom_components.light.lightpack: critical
    homeassistant.components.binary_sensor.skybell_front_door_button: critical
    homeassistant.components.binary_sensor.skybell_front_door_motion: critical
    homeassistant.components.websocket_api.http.connection: critical
    homeassistant.components.hue: critical
    homeassistant.components.light.hue: critical
    homeassistant.components.device_tracker.netgear: critical
    homeassistant.helpers.entity_component: critical
    homeassistant.helpers.entity: critical
    homeassistant.loader: critical
    
history: !include structure/history.yaml

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_secret
  max_retries: 3
  default_measurement: state

logbook:
  exclude:
    domains:
      - group
      - sensor
      - device_tracker
      - android_ip_webcam
    entities:
      - switch.webcam_video_recording
      - automation.update_watt_hour
      - automation.keep_windows_open
      - automation.temperature_vacation
  include:
    entities:
      - device_tracker.kenny_pixelc
      - person.kenny
      - person.meredith
      - device_tracker.mere_lap
      - device_tracker.pc

# custom_updater:
  # show_installable: false
  # track:
    # - components
    # - cards
  # card_urls:
    # - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json
    # - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    # - https://raw.githubusercontent.com/maykar/custom-lovelace/master/tracker.json
  # component_urls:
    # - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
    # - https://raw.githubusercontent.com/keatontaylor/custom_components/master/custom_components.json

hacs:
  token: !secret hacs_token
  appdaemon: true
  python_script: true
  theme: true

breaking_changes:
  scan_interval: 1800
    
frontend: !include structure/theme.yaml

lovelace:

python_script:

zwave:
  usb_path: /dev/ttyACM0
  device_config:
    light.dining_lights_level:
      refresh_value: true

emulated_hue: !include assistant/emulated_hue.yaml

#cloud: !include assistant/cloud.yaml
      
automation: !include intelligence/automations.yaml

scene: !include intelligence/scene.yaml

script: !include intelligence/scripts.yaml

zone: !include structure/zone.yaml

group: !include structure/groups.yaml

config:

discovery:

ssdp:

zeroconf:

device_tracker:
  - platform: bluetooth_tracker
    request_rssi: true
  - platform: netgear
    host: !secret router_ip
    username: !secret wifi_username
    password: !secret wifi_password
    port: 5000
    devices:
      - !secret kcell_mac
      - !secret mcell_mac
      - !secret kworkcell_mac
      - !secret mlap_mac
      - !secret nswitch_mac
      - !secret ktab_mac

switch: !include components/switch.yaml

binary_sensor: !include components/binary_sensor.yaml

input_boolean: !include components/input_boolean.yaml

input_number:
  vacuum_repeats:
    name: Repeats
    initial: 1
    min: 1
    max: 3
    step: 1
    
input_select:
  fanmode:
    name: Fan Mode
    icon: mdi:fan
    options:
      - "Quiet"
      - "Balanced"
      - "Turbo"
      - "Max"

sensor: !include components/sensors.yaml

sun:

media_player: !include components/media_player.yaml

light: !include components/lights.yaml

tplink:

alexa_media:
  accounts:
    - email: !secret kemail
      password: !secret amz_secret
      url: amazon.com
      scan_interval: 30

hue:
  bridges:
    - host: !secret hue_ip
      allow_unreachable: true
      allow_hue_groups: true
      
speedtestdotnet:
  scan_interval:
    hours: 1
  monitored_conditions:
    - ping
    - download
    - upload
    
stream:
    
skybell:
    username: !secret kemail
    password: !secret skybell_secret
      
amcrest:
  - host: !secret backyard_IP
    username: !secret backyard_user
    password: !secret backyard_pswd
    name: "Backyard Camera"
    binary_sensors:
      - motion_detected
    port: !secret amcrest_port
    scan_interval: 20
  - host: !secret livingroom_IP
    username: !secret livingroom_user
    password: !secret livingroom_pswd
    name: "Living Room Camera"
    binary_sensors:
      - motion_detected
    port: !secret amcrest2_port
    scan_interval: 20
      
# android_ip_webcam:
  # - host: !secret webcam_ip
    # name: Webcam
    # username: !secret camname_secret
    # password: !secret campass_secret
    # sensors:
      # - audio_connections
      # - battery_level
      # - battery_temp
      # - battery_voltage
      # - light
      # - motion
      # - pressure
    # switches:
      # - exposure_lock
      # - ffc
      # - focus
      # - gps_active
      # - night_vision
      # - overlay
      # - torch
      # - whitebalance_lock
      # - video_recording

ffmpeg:
      
weather:
  - platform: darksky
    api_key: !secret dark_api
    mode: 'daily'

camera:
  - platform: skybell
    monitored_conditions:
    - avatar
    - activity
    activity_name: "Last Activity"
#  - platform: amcrest

vacuum:
  - platform: xiaomi_miio
    host: !secret croc_vac_IP
    token: !secret croc_vac_secret
      
ifttt:
  key: !secret ifttt_key

google:
  client_id: !secret gcal_ID
  client_secret: !secret gcal_secret
 
ecobee:
  api_key: !secret ecobee_key
 
notify:
  - platform: pushbullet
    api_key: !secret push_key
    name: pushbullet
  - platform: alexa_media
    name: alexa_media
  - platform: group
    name: residents
    services:
      - service: pushbullet
      - service: ios_merediths_iphone

panel_iframe:
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: !secret url6_secret