- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: swap_use_percent
    - type: load_1m
    - type: processor_use
    - type: since_last_boot
- platform: history_stats
  name: Meredith
  entity_id: device_tracker.mere_iphone
  state: 'home'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 7
- platform: history_stats
  name: Kenny
  entity_id: device_tracker.kenny_pixelxl
  state: 'home'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 7
- platform: history_stats
  name: Basement 1 Light Hours
  entity_id: light.basement_1
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Basement 2 Light Hours
  entity_id: light.basement_2
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Basement 3 Light Hours
  entity_id: light.basement_3
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Basement 4 Light Hours
  entity_id: light.basement_4
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Rock Lamp Light Hours
  entity_id: light.rock_lamp
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Swirl Lamp Light Hours
  entity_id: light.swirl_lamp
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Sewing Light Hours
  entity_id: light.sewing_light
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Deck Light Hours
  entity_id: light.deck_light
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Floor Lamp Light Hours
  entity_id: light.floor_lamp
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Chair Lamp Light Hours
  entity_id: light.chair_lamp
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Front Door Light Hours
  entity_id: light.front_outside
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Oven Light Hours
  entity_id: light.oven
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Basement Light Hours
  entity_id: switch.outlet
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Bedroom Fan Hours
  entity_id: switch.bedfan
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Craft Room Fan Hours
  entity_id: switch.craftfan
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Office Fan Hours
  entity_id: switch.officefan
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Guest Bedroom Fan Hours
  entity_id: switch.guestbed
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Prep Area Hours
  entity_id: switch.kitchensw
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Master Bathroom Hours
  entity_id: switch.masterbath
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Computer Hours
  entity_id: switch.desktoppc
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: history_stats
  name: Dining Room Light Hours
  entity_id: light.dining_lights_level
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 1
- platform: speedtest
  minute:
    - 0
  monitored_conditions:
    - ping
    - download
    - upload
- platform: wunderground
  api_key: !secret wunderground_api
  monitored_conditions:
    - weather
    - temp_f
    - feelslike_f
    - feelslike_string
    - precip_today_in
    - precip_today_string
    - temp_high_1d_f
    - temp_low_1d_f
    - alerts
    - precip_1d_in
    - precip_1d
- platform: haveibeenpwned
  email:
    - !secret kemail
    - !secret memail
- platform: uptime
- platform: statistics
  entity_id: sensor.webcam_motion
  name: Living Room Motion Stats
  max_age:
    minutes: 5
- platform: cert_expiry
  host: !secret url2_secret
  port: 8123