homeassistant:
  customize: !include _structure/customize.yaml
  customize_domain: {}
  customize_glob: {}

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret url4_secret
  server_port: 443
  
recorder:
  auto_purge: true
  purge_keep_days: 4
  db_url: !secret db_secret

system_health:

person:

logger: 
  default: error
  logs:
    homeassistant.components.visitor.calendar: critical
    homeassistant.components.vacation.calendar: critical
    homeassistant.components.ssl_certificate_expiry.sensor: critical
    custom_components.weatheralerts.sensor: critical
    homeassistant.components.skybell.binary_sensor: critical
    homeassistant.components.skybell.switch: critical
    homeassistant.components.skybell.sensor: critical
    homeassistant.components.skybell_front_door_motion.binary_sensor: critical
    homeassistant.components.skybell_front_door_button.binary_sensor: critical
    homeassistant.components.skybell_front_door_do_not_disturb.switch: critical
    homeassistant.components.front_door.light: critical
    homeassistant.components.websocket_api.http.connection: critical
    homeassistant.components.hue: critical
    homeassistant.components.hue.light: critical
    homeassistant.components.emulated_hue: critical
    homeassistant.components.netgear.device_tracker: critical
    custom_components.netgear_enhanced.sensor: critical
    custom_components.netgear_enhanced.switch: critical
    # homeassistant.components.netgear: debug
    # custom_components.netgear_enhanced.sensor: debug
    # custom_components.netgear_enhanced.switch: debug
    homeassistant.components.yamaha.media_player: critical
    # custom_components.thingy52.sensor: debug
    custom_components.lightpack.sensor: critical
    # custom_components.auto_backup: debug
    # homeassistant.components.python_script: debug
    
history: !include _structure/history.yaml

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_secret
  max_retries: 3
  default_measurement: state

logbook:
  exclude:
    domains:
      - group
      - sensor
      - device_tracker
      - android_ip_webcam
    entities:
      - switch.webcam_video_recording
      - automation.update_watt_hour
      - automation.keep_windows_open
      - automation.temperature_vacation
  include:
    entities:
      - device_tracker.kenny_pixelc
      - person.kenny
      - person.meredith
      - device_tracker.mere_lap
      - device_tracker.pc

breaking_changes:
  scan_interval: 1800
    
frontend:
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar.js
  themes: !include_dir_merge_named themes

lovelace:

python_script:

zwave:
  usb_path: /dev/ttyACM0
  device_config:
    light.dining_lights_level:
      refresh_value: true

# emulated_hue: !include assistant/emulated_hue.yaml

# cloud: !include assistant/cloud.yaml

alexa: !include assistant/alexa.yaml

api:
      
automation: !include _intelligence/automations.yaml

scene: !include _intelligence/scene.yaml

script: !include _intelligence/scripts.yaml

group: !include _structure/groups.yaml

config:

# config_check:

updater:

discovery:

mobile_app:

ssdp:

zeroconf:

device_tracker:
  # - platform: bluetooth_le_tracker
    # track_new_devices: true
  # - platform: bluetooth_tracker
    # request_rssi: true
  # - platform: netgear
    # # url: !secret router_url
    # host: !secret router_ip
    # username: !secret wifi_username
    # password: !secret wifi_password
    # port: 5000
    # devices:
      # - !secret kcell_mac
      # - !secret mcell_mac
      # - !secret kworkcell_mac
      # - !secret mlap_mac
      # - !secret nswitch_mac
      # - !secret ktab_mac
    # # accesspoints:
      # # - !secret kcell_mac
      # # - !secret mcell_mac

switch: !include _components/switch.yaml

binary_sensor: !include _components/binary_sensor.yaml

input_boolean: !include _components/input_boolean.yaml
    
input_select:
  fanmode:
    name: Fan Mode
    icon: mdi:fan
    options:
      - "Silent"
      - "Standard"
      - "Medium"
      - "Turbo"

input_number:
  ssl_cert:
    name: SSL Certificate
    min: -20
    max: 100
    icon: mdi:certificate
  watthour:
    name: Daily Total Usage
    min: 0
    max: 50
    icon: mdi:power-socket-us
    unit_of_measurement: 'kWh'
  cpuhour:
    name: CPU Total Usage
    min: 0
    max: 50
    icon: mdi:power-socket-us
    unit_of_measurement: 'kWh'
  lighthour:
    name: Light Total Usage
    min: 0
    max: 50
    icon: mdi:power-socket-us
    unit_of_measurement: 'kWh'

counter: !include _components/counter.yaml

sensor: !include _components/sensors.yaml

plant: !include _components/plant.yaml

sun:

media_player: !include _components/media_player.yaml

light: !include _components/lights.yaml

tplink:
  # discovery: false
  # switch:
    # - host: !secret outlet_ip
    # - host: !secret airhockey_ip
    # - host: !secret bedfan_ip
    # - host: !secret nurseryfan_ip
    # - host: !secret craftfan_ip
    # - host: !secret masterbath_ip
    # - host: !secret kitchen_ip
    # - host: !secret guestbed_ip
    # - host: !secret sunroom_ip

momentary:

hue:
  bridges:
    - host: !secret hue_ip
      allow_unreachable: true
      allow_hue_groups: true
      
speedtestdotnet:
    
stream:
    
skybell:
    username: !secret kemail
    password: !secret skybell_secret
      
amcrest:
  - host: !secret backyard_IP
    username: !secret backyard_user
    password: !secret backyard_pswd
    name: "Backyard Camera"
    binary_sensors:
      - motion_detected
    port: !secret amcrest_port
    scan_interval: 20
  - host: !secret livingroom_IP
    username: !secret livingroom_user
    password: !secret livingroom_pswd
    name: "Living Room Camera"
    binary_sensors:
      - motion_detected
    port: !secret amcrest2_port
    scan_interval: 20
  - host: !secret nursery_IP
    username: !secret nursery_user
    password: !secret nursery_pswd
    name: "Nursery Camera"
    binary_sensors:
      - motion_detected
    port: !secret amcrest3_port
    scan_interval: 20

ffmpeg:

camera:
  - platform: skybell
    monitored_conditions:
    - avatar
    - activity
    activity_name: "Last Activity"

vacuum:
  - platform: xiaomi_miio
    host: !secret cop_vac_IP
    token: !secret cop_vac_secret
      
ifttt:
  key: !secret ifttt_key

google:
  client_id: !secret gcal_ID
  client_secret: !secret gcal_secret
 
ecobee:
  api_key: !secret ecobee_key
  
webostv:
  host: !secret lg_ip
  name: Living Room TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret lg_mac
  customize:
    sources:
      - Amazon Prime Video
      - Disney+
      - Google Play Movies & TV
      - Netflix
      - YouTube
      - YouTube TV
 
notify:
  - platform: alexa_media
    name: alexa_media
  - platform: group
    name: residents
    services:
      - service: mobile_app_pixel_3a_xl
      - service: mobile_app_iphone
  - platform: group
    name: everything
    services:
      - service: mobile_app_pixel_3a_xl
      - service: mobile_app_iphone
      - service: living_room_tv

# auto_backup:
  # auto_purge: true
  # backup_timeout: 2400
